					<option value="0">Question category</option>
					<option value="43">Address-related</option>
					<option value="74">Balloting issues</option>
					<option value="44">Deadlines</option>
					<option value="50">Eligibility</option>
					<option value="46">Federal Write-in Absentee Ballot</option>
					<option value="48">Form Related Questions</option>
					<option value="51">Glossary</option>
					<option value="47">Party Affiliation</option>
					<option value="49">Primary Elections</option>
					<option value="57">Registration Issues</option>
					<option value="52">Related Issues</option>
					<option value="54">Security</option>
					<option value="45">U.S. Citizens without Residency</option>
					<option value="55">Uniformed Services Voters</option>
					<option value="58">Voter Account Questions</option>
					<option value="53">Voter Identification</option>
					<option value="81">Technical Questions</option>
