<%--
  Created by IntelliJ IDEA.
  User: Leo
  Date: Jul 14, 2008
  Time: 9:04:19 PM
  To change this template use File | Settings | File Templates.
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core_rt"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jstl/fmt_rt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>


<div class="content-pad">

    <spring:bind path="expressForm.fedexLabel">
        <c:choose>
            <c:when test="${status.error}">
                <h2>Waybill Error Information</h2>
        		<div class="error-indicator">
                <c:forEach items="${status.errorMessages}" var="message">
                    <p>${message}</p>
                </c:forEach>
                </div>
            </c:when>
            <c:otherwise>
                <c:if test="${imageLabel}">
                    <img src="<c:url value="/LabelImage.htm"><c:param name="tracking">${expressForm.fedexLabel.trackingNumber}</c:param></c:url>" alt="" width="700" />
                    <p>VOTE EXPRESS REFERENCE NUMBER: 918273</p>
                    <p class="fedex-label-warning">WARNING: USE ONLY THE PRINTED
						ORIGINAL LABELS FOR SHIPPING TO ENSURE THE TIMELY DELIVERY OF YOUR
						PACKAGE. YOU MUST PLACE THREE ORIGINALS OF THIS TWO PAGE AIR WAYBILL IN THE
						POUCH ACCOMPANYING YOUR PACKAGE.</p>
					<p class="fedex-label-tc">
						<!--CONDITIONS OF CONTRACT Definitions: On this Air Waybill, "we", "our", "us", and "FedEx" refer to Federal Express Corporation, its subsidiaries, affiliates and branches and their respective employees, agents, and independent contractors.  The terms  "you" and "your" refer to the shipper, its employees, principals and agents.  If your shipment originates outside the United States, your contract of carriage is with the FedEx subsidiary, branch or independent contractor who originally accepts the shipment from you.  The term "package" means any container or envelope that is accepted by us for delivery, including any such items tendered by you utilizing our automated systems, meters, manifests or waybills.  The term "shipment" means all packages which are tendered to and accepted by us on a single Air Waybill.  Agreement To Terms: By processing and giving us your shipment, you agree, regardless of whether you sign the front of this Air Waybill, for yourself and as agent for and on behalf of any other person having an interest in this shipment, to all terms on this NON-NEGOTIABLE Air Waybill, and as appropriate, to all terms in any FedEx transportation agreement between you and FedEx covering this shipment and in any applicable tariff, and in our current applicable Service Guide, or Standard Conditions of Carriage, copies of which are available upon request.  If there is a conflict between this Air Waybill and any such document then in effect, the transportation agreement, tariff, Service Guide or Standard Conditions of Carriage will control in that order of priority.  No one is authorized to alter or modify the terms of our agreement.  This Air Way bill shall be binding on us when the shipment is accepted: we may mark this Air Waybill with an employee number as our signature, or our printed name shall be sufficient to constitute our signature of this Air Waybill.  Your Obligations - Printed Signature: You acknowledge that if you process shipments to locations outside the country where your shipment originates, you must enter, to print in lieu of a manual signature on the Air Waybill, the name of the person completing the Air 
						Waybill for all such shipments tendered to FedEx by you using this application.  You further acknowledge that such printed name shall be sufficient to constitute your signature on the Air Waybill and acceptance of FedEx's terms and conditions of carriage for purposes of the Warsaw Convention, an international treaty related to international carriage by air and any of its subsequent amendments and protocols thereto, (collectively ìWarsaw Conventionî) and for all other purposes.  You warrant that each article in each shipment is properly described on this Air Waybill and any export documents, is acceptable for transport by FedEx, and that the shipment is properly marked, addressed and packed to ensure safe transportation with ordinary care in handling.  You are responsible for all charges, including transportation charges and possible surcharges and customs and duties assessments, including fees related to our payment of the same, governmental penalties and fines, taxes and FedEx legal costs related to your shipment.  Air Carriage Notice:  IF THE CARRIAGE OF YOUR SHIPMENT BY AIR INVOLVES AN ULTIMATE DESTINATION OR STOP IN A COUNTRY OTHER THAN THE COUNTRY OF DEPARTURE, THE WARSAW CONVENTION MAY BE APPLICABLE, WHICH TREATY WOULD THEN GOVERN AND IN MOST CASES LIMIT FEDEX'S LIABILITY FOR LOSS, DELAY OF, SHORTAGE, MISDELIVERY, NONDELIVERY MISINFORMATION, DAMAGE  OR FAILURE TO PROVIDE INFORMATION IN CONNECTION WITH YOUR SHIPMENT.  In certain countries, the Warsaw Convention limits FedExís liability to U.S. $9.07 per pound (U.S. $20.38 per kilogram or equivalent local currency for the country of origin), unless a higher value for carriage is declared as described below and you  pay any applicable supplementary charges.  The interpretation and operation of the Warsaw convention's liability limits may vary in each country.  There are no stopping places which are agreed to and FedEx reserves the right to route the shipment in any way FedEx deems appropriate.  Road Transport Notice:  Shipments transported partly or solely by road, be 
						there an explicit agreement to do so or not, into or from a country which is a party to the Convention on the Contract for the International Carriage of Goods by Road (the "CMR") are subject to the terms and conditions of the CMR, notwithstanding any other provision referred to or in this Air Waybill to the contrary except that the higher limitations of liability as set forth in these conditions shall remain applicable as opposed to those set forth in the CMR.  Limitation of Liability:  If not governed by the Warsaw Convention, the CMR, or other international treaties, laws, other government regulations, orders, or requirements, FedEx's maximum liability for loss, damage, delay, shortage, misdelivery, nondelivery, misinformation or the failure to provide information in connection with your shipment is limited by this Air Waybill to the greater of the amount of U.S. $100 or U.S. $9.07 per pound (U.S. $20.38 per kilo) (or equivalent local currency for the country of origin)  whichever is greater (or in Canada, the amount of actual damages or CDN$100 per shipment, whichever is less).  If you declare a higher value you must pay an additional charge for each additional U.S. $100 or the equivalent in local currency in declared value for carriage.  Please call us or refer to our rate sheets in effect at the time of shipment for an explanation of the additional charge.  If you declare a higher value for carriage and pay the additional charge, our maximum liability will be the lesser of your declared value for carriage or your actual damages.  FedEx does not provide cargo liability or all-risk insurance, but you may pay an additional charge for each additional U.S. $100 (or equivalent local currency for the country of origin) (or in Canada CAN $100) of declared value for carriage.  If a higher value for carriage is declared and the additional charge is paid, FedEx's maximum liability will be the lesser of the declared value for carriage or your actual damages.  Declared Value Limits:  The highest declared value FedEx allows for a FedEx Letter/Envelope and FedEx Pak shipment is US$100 or US$9.07 per pound (US$20.38 per kilo)(or the equivalent in local currency), whichever is greater.  In Canada, 
						the maximum declared value allowed for customs and carriage per Air Waybill for each FedEx Letter and FedEx Pak is CAN$100.  For other shipments, in particular shipments of extraordinary value, including, but not limited to jewelry, artwork, antiques, precious metals, and furs and fur clothing, the declared value of carriage is limited and depends on the contents and the destination of the shipment.  Please check the applicable Service Guide, contract of carriage, transportation agreement, tariff, or Standard Conditions for an explanation of the declared value limits.  If you send more than one package using a single Air Waybill, the declared value for carriage of each package will be determined by dividing the total declared value for carriage by the number of packages in the shipment.  For shipments tendered for FedEx Ground service please reference the applicable Service Guide.  Liabilities Not Assumed.  IN ANY EVENT, SUBJECT TO THE SERVICE CONDITIONS ON THIS AIR WAYBILL, OR THE APPLICABLE SERVICE GUIDE, TRANSPORTATION AGREEMENT, STANDARD CONDITIONS, TARIFF OR CONTRACT OF CARRIAGE, FEDEX WON'T BE LIABLE FOR ANY DAMAGES, WHETHER DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL, IN EXCESS OF THE DECLARED VALUE US$100 OR US$9.07 PER LB. (US$20.38 PER KILO) (OR THE EQUIVALENT IN LOCAL CURRENCY) WHICHEVER IS GREATER (OR IN CANADA IN EXCESS OF THE DECLARED VALUE FOR CARRIAGE) (INCLUDING BUT NOT LIMITED TO LOSS OF INCOME OR PROFITS) WHETHER OR NOT FEDEX KNEW OR SHOULD HAVE KNOWN THAT SUCH DAMAGES MIGHT BE INCURRED INCLUDING BUT NOT LIMITED TO LOSS OD INCOME OR PROFITS.  FedEx won't be liable for your acts or omissions, including but not limited to incorrect declaration of cargo, improper or insufficient packing, securing, marking or addressing of the shipment, or for the acts or omissions of the recipient or anyone else with an interest in the shipment.  Also, FedEx won't be liable if you or the recipient violate any of the terms of our Agreement.  
						FedEx won't be liable for loss, damage, delay, shortage, misdelivery, nondelivery, misinformation or failure to provide information (i) in connection with shipments of cash, currency, or other prohibited items; or, (ii) caused by events FedEx cannot control, including but not limited to acts of God, perils of the air, weather conditions, mechanical delays, acts of public enemies, war, strikes, civil commotions, or acts or omissions of public authorities (including customs and health officials) with actual or apparent authority.  No Warranty:  We make no warranties, express or implied.  Claims for Loss, Damage or Delay:  ALL CLAIMS MUST BE MADE IN WRITING AND WITHIN STRICT TIME LIMITS.  SEE OUR APPLICABLE TARIFF, SERVICE GUIDE, OR STANDARD CONDITIONS OF CARRIAGE FOR DETAILS.  The Warsaw Convention provides that written claims for damage must be received within 14 days from the date of receipt and within twenty-one days in the event of delay.  FedEx may have expanded the claims periods in certain countries and the periods may differ from country to country.  Moreover, the interpretation and operation of the Warsaw Convention's claims provisions may vary in each country.  Contact the FedEx representative in the country of origin to determine the claims period for your shipment.  In the event of nondelivery, misdelivery, misinformation or failure to provide information, we must receive written notice of the claim within 90 days after we accept the shipment.  The right to damages against us regarding a shipment shall be extinguished unless an action is brought within two years from the date of delivery of the shipment or from the date on which the shipment should have been delivered, or from the date on which the carriage stopped.  Within 90 days after notification to us of the claim, it must be documented by sending us all relevant information about it.  FedEx is not obligated to act on any claim until all transportation charges have been paid.  The claim amount may not be deducted from the those charges.  If the recipient accepts the shipment without noting any damage on the delivery record, FedEx will assume the shipment 
						was delivered in good condition.   In order for us to consider a claim for damage, the contents, original shipping carton and packing must be made available to us for inspection.  Right to Inspect:  Your shipments may, at FedEx's option, or at the request of customs or other regulatory or government authorities, be opened and inspected by FedEx or such authorities at any time.  Responsibility For Payment:  Even if you give FedEx different payment instructions, you will always be primarily responsible for all charges, including transportation charges, and possible surcharges, customs and duties assessments, including fees related to our prepayment of the same governmental penalties and fines, taxes, and FedEx's lawyersí fees and legal costs, related to this shipment.  You also will be responsible for any costs FedEx may incur in returning your shipments to you or warehousing them pending disposition.  Customs Clearance:  By giving us this shipment, you hereby appoint FedEx, or its independent contractor as applicable, as your agent solely for performance of customs clearance and certify FedEx as the nominal consignee for the purpose of designating a customs broker to perform customs clearance.  In some instances, local authorities may require additional documentation confirming FedEx's appointment.  It is your responsibility to provide proper documentation and confirmation, when required.  You are responsible for and warrant your compliance with all applicable laws, rules and regulations, including but not limited to customs laws, import, import, export  and reexport laws and government regulations of any country to, from, through or over which your shipments may be carried.  You agree to furnish such information and complete and attach to the this Air Waybill such documents as are necessary to comply with such laws, rules and regulations.  FedEx assumes no liability to you or any other person for any loss or expense due to your failure to comply with this provision.  You are also responsible for all charges, including transportation charges, and all duties, customs assessments, governmental penalties and fines, taxes, and FedEx lawyer's fees and 
						legal costs, related to any shipment.  Letter of Instruction:  If you do not complete all the documents required for carriage or if the documents submitted are not appropriate for the services or destination requested, you hereby instruct FedEx, or its independent contractor, as applicable, where permitted by law to complete, correct or replace the documents for you at your expense.  However, FedEx is not obligated to do so.  If a substitute form of air waybill is needed to complete delivery of your shipment and FedEx completes that document, the terms of this Agreement will continue to govern.  FedEx is not liable to you or any other person for FedEx's actions on your behalf under this provision. Items Not Acceptable for Transportation: FedEx does not accept transportation of money (including, but not limited to, coins (except collectible) or negotiable instruments equivalent to cash such as endorsed stocks and bonds.)  FedEx excludes all liability for shipments of such items accepted by mistake.  Other items may be accepted for carriage only to limited destinations or under restricted conditions.  FedEx reserves the right to reject packages based upon these limitations or for reasons of safety or security.  You may consult the applicable Service Guide, contract of carriage, tariff or Standard Conditions for specific details.  Export Control.  You authorize FedEx, and its independent contractors, as applicable, to act as forwarding agent for you for export and customs purposes.  You hereby certify that all statements and information contained on all Air Waybills, SEDs and accompanying documentation relating to exportation are true and correct.  You further certify that all Commercial Invoice information submitted via API is true and correct.  You expressly authorize FedEx and its independent contractors, as applicable, to forward all information of any nature regarding shipments to any and all governmental or regulatory agencies which request or require such information.  Furthermore, you understand that civil and criminal penalties, including forfeiture and sale, may be imposed for making false or fraudulent statements or for the violation of any country laws on exportation,
						including but not limited to, for shipments originating in the U.S., 13 U.S.C. ß305; 22 U.S.C. ß401; 18 U.S.C. ß1001; and 50 U.S.C. App. 2410, and for shipments originating in Canada, the Export and Import Permits Act, R.S.C. E-17.  Consult the laws in the country of origin for similar restrictions.  You acknowledge that no shipments tendered by you from the United States using API will be sent to any entity listed on the Department of Commerce's Denied Parties List 15 C.F.R. Part 764, Supp. 2, or the list of Special Designated Nationals as published by the Office of Foreign Assets Control of the U.S. Department of the Treasury and that you are neither a denied party or a specially designated national.  Consult the laws of the origin country of your shipment for similar provisions.  Mandatory Law:  Insofar as any provision contained or referred to in the Air Waybill may be contrary to any applicable international treaties, laws, governmental regulations, orders or requirements, such provision shall remain in effect as part of our agreement to the extent that it is not overridden.  The invalidity or unenforceability of any provision shall not affect any other provision contained or referred to in the Air Waybill.  Unless otherwise indicated, the shipperís address indicated on the face of the Air Waybill is the place of execution and the place of departure and the recipientís address listed on the face of the Air Waybill is the place of destination. Unless otherwise indicated on the face of the Air Waybill, label manifest or pick-up record, the first carrier of this shipment is Federal Express Corporation, P.O. Box 727, Memphis, TN 38194. 
						-->
						LEGAL TERMS AND CONDITIONS OF FEDEX SHIPPING DEFINITIONS. On this Air Waybill, "we", "our", "us", and "FedEx" refer to Federal Express Corporation, its subsidiaries and branches and their respectiveemployees, agents, and independent contractors. The terms "you" and "your" refer to the shipper, its employees, principals and agents. If your shipment originates outside the United States, your contract of carriage iswith the FedEx subsidiary, branch or independent contractor who originally accepts the shipment from you. The term "package" means any container or envelope that is accepted by us for delivery, including any suchitems tendered by you utilizing our automated systems, meters, manifests or waybills. The term "shipment" means all packages which are tendered to and accepted by us on a single Air Waybill. AIR CARRIAGENOTICE. For any international shipments by air, the Warsaw Convention, as amended, may be applicable. The Warsaw Convention, as amended, will then govern and in most cases limit FedEx's liability for loss, delayof, or damage to your shipment. The Warsaw Convention, as amended, limits FedEx's liability. For example in the U.S. liability is limited to $9.07 per pound (20$ per kilogram), unless a higher value for carriage isdeclared as described below and you pay any applicable supplementary charges. The interpretation and operation of the Warsaw Convention's liability limits may vary in each country. There are no specific stoppingplaces which are agreed to and FedEx reserves the right to route the shipment in any way FedEx deems appropriate. ROAD TRANSPORT NOTICE. Shipments transported solely by road to or from a country which isa party to the Warsaw Convention or the Contract for the International Carriage of Goods by Road (the "CMR") are subject to the terms and conditions of the CMR, notwithstanding any other provision of this Air Waybillto the contrary. For those shipments transported solely by road, if a conflict arises between the provisions of the CMR and this Air Waybill, the terms of the CMR shall prevail. LIMITATION OF LIABILITY. If notgoverned by the Warsaw Convention, the CMR, or other international treaties, laws, other government regulations, orders, or 
						requirements, FedEx's maximum liability for damage, loss, delay, shortage, mis-delivery,nondelivery, misinformation or failure to provide information in connection with your shipment is limited by this Agreement and as set out in the terms and conditions of the contract of carriage. Please refer to thecontract of carriage set forth in the applicable FedEx Service Guide or its equivalent to determine the contractual limitation. FedEx does not provide cargo liability or all -risk insurance, but you may pay an additionalcharge for each additional U.S. $100 (or equivalent local currency for the country of origin) of declared value for carriage. If a higher value for carriage is declared and the additional charge is paid, FedEx's maximumliability will be the lesser of the declared value for carriage or your actual damages. LIABILITIES NOT ASSUMED. IN ANY EVENT, FEDEX WON'T BE LIABLE FOR ANY DAMAGES, WHETHER DIRECT, INDIRECT,INCIDENTAL, SPECIAL OR CONSEQUENTIAL IN EXCESS OF THE DECLARED VALUE FOR CARRIAGE (INCLUDING BUT NOT LIMITED TO LOSS OF INCOME OR PROFITS) OR THE ACTUAL VALUE OFTHE SHIPMENT, IF LOWER, WHETHER OR NOT FEDEX HAD ANY KNOWLEDGE THAT SUCH DAMAGES MIGHT BE INCURRED. FedEx won't be liable for your acts or omissions, including but not limited toincorrect declaration of cargo, improper or insufficient packaging, securing, marking or addressing of the shipment, or for the acts or omissions of the recipient or anyone else with an interest in the shipment orviolations by any party of the terms of this agreement. FedEx won't be liable for damage, loss, delay, shortage, mis -delivery, non-delivery, misinformation or failure to provide information in connection with shipments ofcash, currency or other prohibited items or in instances beyond our control, such as acts of God, perils of the air, weather conditions, mechanical delays, acts of public enemies, war, strike, civil commotion, or acts oromissions of public authorities(including customs and health officials) with actual or apparent authority. NO WARRANTY. We make no warranties, express or implied. CLAIMS FOR LOSS, DAMAGE OR DELAY. ALLCLAIMS MUST BE MADE IN WRITING AND WITHIN STRICT TIME LIMITS. SEE OUR TARIFF, APPLICABLE 
						FEDEX SERVICE GUIDE, OR STANDARD CONDITIONS OF CARRIAGE FOR DETAILS. The WarsawConvention provides specific written claims procedures for damage, delay or non-delivery of your shipment. Moreover, the interpretation and operation of the Warsaw Convention's claims provisions may vary in eachcountry. Refer to the Convention to determine the claims period for your shipment. The right to damages against us shall be extinguished unless an action is brought within two years, as set forth in the Convention.FedEx is not obligated to act on any claim until all transportation charges have been paid. The claim amount may not be deducted from the transportation charges. If the recipient accepts the shipment without notingany damage on the delivery record, FedEx will assume the shipment was delivered in good condition. In order for us to consider a claim for damage, the contents, original shipping carton and packing must be madeavailable to us for inspection. MANDATORY LAW. Insofar as any provision contained or referred to in this Air Waybill may be contrary to any applicable international treaties, laws, government regulations, orders orrequirements such provisions shall remain in effect as a part of our agreement to the extent that it is not overridden. The invalidity or unenforceability of any provisions shall not affect any other part of this Air Waybill.Unless otherwise indicated, FEDERAL EXPRESS CORPORATION, 2005 Corporate Avenue, Memphis, TN 38132, USA, is the first carrier of this shipment. Email address located at www.fedex.com.
					</p>
					<p><a class="print" href="#" onclick="window.print(); return false;"><img src="<c:url value='/img/buttons/print-waybill-button.gif'/>" /></a></p>
                </c:if>
            </c:otherwise>
        </c:choose>
    </spring:bind>

</div>