---
apiVersion: v1
kind: Secret
metadata: 
  name: ovf-env-secrets
type: Opaque
stringData:
  ENV: "{{ .Values.ENV }}"
  ENVIRONMENT: "{{ .Values.ENVIRONMENT }}"
  AUTHORIZE_NET_KEY: "{{ .Values.AUTHORIZE_NET_KEY}}"
  AUTHORIZE_NET_LOGIN: "{{ .Values.AUTHORIZE_NET_LOGIN }}"
  DB_PASS: "{{ .Values.DB_PASS }}"
  DB_URL: "{{ .Values.DB_URL }}"
  DB_USER: "{{ .Values.DB_USER }}"
  EOD_API_SERVICE_URL: "{{ .Values.EOD_API_SERVICE_URL }}"
  FACT_CHECK_KEY: "{{ .Values.FACT_CHECK_KEY}}"
  FEDEX_AUTH_KEY: "{{ .Values.FEDEX_AUTH_KEY }}"
  FEDEX_AUTH_PASS: "{{ .Values.FEDEX_AUTH_PASS }}"
  FEDEX_CLIENT_NUM: "{{ .Values.FEDEX_CLIENT_NUM }}"
  FEDEX_METER_NUM: "{{ .Values.FEDEX_METER_NUM }}"
  IMAGE_VERSION: "{{ .Values.IMAGE_VERSION }}"
  IS_JOB_ENABLED: "{{ .Values.IS_JOB_ENABLED }}"
  IVOTE_ISRAEL_PASS: "{{ .Values.IVOTE_ISRAEL_PASS }}"
  IVOTE_ISRAEL_PORT: "{{ .Values.IVOTE_ISRAEL_PORT }}"
  IVOTE_ISRAEL_SERVER: "{{ .Values.IVOTE_ISRAEL_SERVER}}"
  IVOTE_ISRAEL_SFTP_DIR: "{{ .Values.IVOTE_ISRAEL_SFTP_DIR}}"
  IVOTE_ISRAEL_USER: "{{ .Values.IVOTE_ISRAEL_USER}}"
  JEDIS_DB: "{{ .Values.JEDIS_DB }}"
  JEDIS_ENABLED: "{{ .Values.JEDIS_ENABLED}}"
  JEDIS_HOST: "{{ .Values.JEDIS_HOST}}"
  JEDIS_PORT: "{{ .Values.JEDIS_PORT}}"
  LOCAL_ELECTION_AUTH_TOKEN: "{{ .Values.LOCAL_ELECTION_AUTH_TOKEN }}"
  LOCAL_ELECTION_URL: "{{ .Values.LOCAL_ELECTION_URL }}"
  MAIL_HOST: "{{ .Values.MAIL_HOST}}"
  MAIL_LOGIN: "{{ .Values.MAIL_LOGIN }}"
  MAIL_PASS: "{{ .Values.MAIL_PASS }}"
  MAIL_PORT: "{{ .Values.MAIL_PORT }}"
  MAIL_TLS: "{{ .Values.MAIL_TLS}}"
  RECAPTCHA_SECRET_KEY: "{{ .Values.RECAPTCHA_SECRET_KEY }}"
  RECAPTCHA_SECRET_KEY_SKIMM: "{{ .Values.RE_CAPTCHA_SITE_KEY_SKIMM }}"
  RECAPTCHA_SECRET_KEY_VOTE411: "{{ .Values.RECAPTCHA_SECRET_KEY_VOTE411 }}"
  RECAPTCHA_SITE_KEY: "{{ .Values.RECAPTCHA_SITE_KEY }}"
  RE_CAPTCHA_SITE_KEY_SKIMM: "{{ .Values.RE_CAPTCHA_SITE_KEY_SKIMM}}"
  RE_CAPTCHA_SITE_KEY_VOTE411: "{{ .Values.RE_CAPTCHA_SITE_KEY_VOTE411 }}"
  S3_ACCESS_KEY: "{{ .Values.S3_ACCESS_KEY }}"
  S3_PATH: "{{ .Values.S3_PATH}}"
  S3_SECRET_KEY: "{{ .Values.S3_SECRET_KEY }}"
  SENDGRID_API_KEY: "{{ .Values.SENDGRID_API_KEY }}"
  SKIMM_MAIL_HOST: "{{ .Values.SKIMM_MAIL_HOST }}"
  SKIMM_MAIL_LOGIN: "{{ .Values.SKIMM_MAIL_LOGIN }}"
  SKIMM_MAIL_PASS: "{{ .Values.SKIMM_MAIL_PASS }}"
  SKIMM_MAIL_PORT: "{{ .Values.SKIMM_MAIL_PORT }}"
  SKIMM_MAIL_TLS: "{{ .Values.SKIMM_MAIL_TLS }}"
  SKIMM_SES_CONFIGSET: "{{ .Values.SKIMM_SES_CONFIGSET }}"
  VOTE411_SES_CONFIGSET: "{{ .Values.VOTE411_SES_CONFIGSET}}"
  VOTE_SMART_KEY: "{{ .Values.VOTE_SMART_KEY }}"
  ZOHO_USER: "{{ .Values.ZOHO_USER}}"
  ZOHO_CLIENT_ID: "{{ .Values.ZOHO_CLIENT_ID}}"
  ZOHO_CLIENT_SECRET: "{{ .Values.ZOHO_CLIENT_SECRET}}"
  # ZOHO_GRANT_TOKEN: "{{ .Values.ZOHO_GRANT_TOKEN}}"
  # ZOHO_DB_HOST: "{{ .Values.ZOHO_DB_HOST}}"
  # ZOHO_DB_DATABASE: "{{ .Values.ZOHO_DB_DATABASE}}"
  # ZOHO_DB_TABLE: "{{ .Values.ZOHO_DB_TABLE}}"
  # ZOHO_DB_PORT: "{{ .Values.ZOHO_DB_PORT}}"
  ZOHO_LOG_PATH: "{{ .Values.ZOHO_LOG_PATH}}"
  ZOHO_RESOURCE_PATH: "{{ .Values.ZOHO_RESOURCE_PATH}}"