---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ovf.fullname" . }}
  annotations:
    # service.beta.kubernetes.io/aws-load-balancer-type: internal
    # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    # service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    # service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:477658251325:certificate/6ca07340-a846-4035-9b97-ae8595145f53
    # service.beta.kubernetes.io/aws-loadbalancer-hostname: stage.overseasvotefoundation.org
    # service.beta.kubernetes.io/aws-loadbalancer-redirect-http-to-https: "true"
    # service.beta.kubernetes.io/aws-loadbalancer-tls-ports: "443"
  labels:
    {{- include "ovf.labels" . | nindent 4 }}
spec:
  type: "NodePort"
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http1
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https

  selector:
    {{- include "ovf.selectorLabels" . | nindent 4 }}


