SET FOREIGN_KEY_CHECKS = 0;

DROP DATABASE IF EXISTS test_overseas;
CREATE DATABASE test_overseas DEFAULT CHARACTER SET utf8;
GRANT SELECT, INSERT, UPDATE, CREATE, DELETE, DROP, LOCK TABLES, ALTER ON test_overseas.* TO testoverseas@localhost
     IDENTIFIED BY 'testoverseas';

SET FOREIGN_KEY_CHECKS = 1;